---
# tasks file for vault_ssh_setup
- name: Ensure dependencies are installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ dependencies }}"

- name: Ensure sshd is running
  ansible.builtin.service:
    name: sshd
    state: started
    enabled: true

- name: Download Vault's public key
  ansible.builtin.get_url:
    url: "{{ vault_public_key_url }}"
    dest: "/etc/ssh/trusted-user-ca-keys.pem"
    mode: "0644"

- name: Check if sshd_config is configured to use the trusted CA keys
  ansible.builtin.command: "grep -q '^TrustedUserCAKeys /etc/ssh/trusted-user-ca-keys.pem' /etc/ssh/sshd_config"
  register: trusted_user_ca_keys_configured
  changed_when: false
  failed_when: false

- name: Configure sshd to use the trusted CA keys
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?TrustedUserCAKeys'
    line: 'TrustedUserCAKeys /etc/ssh/trusted-user-ca-keys.pem'
    state: present
  notify: Set SSHD to be reloaded
  when: not trusted_user_ca_keys_configured.stdout

- name: Ensure PubkeyAuthentication is enabled
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PubkeyAuthentication"
    line: "PubkeyAuthentication yes"
    state: present
  notify: Restart ssh

- name: Create users
  ansible.builtin.user:
    name: "{{ item }}"
    state: present
    createhome: yes
    shell: /bin/bash
  loop: "{{ users_list }}"

- name: Include hardening tasks
  ansible.builtin.include_tasks: hardening.yml
  when: hardening | default(False) | bool
