---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "robertdebock/ubuntu"
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    ansible.builtin.command: "/lib/systemd/systemd"
provisioner:
  name: ansible
verifier:
  name: ansible
